# -*- coding: utf-8 -*-
"""Autism Classification Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l33XyPqoQPuilsSyorUp-BTExZ5z_Gdc

# Data Preprocessing

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Data Preprocessing"""

import zipfile
import os
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split


zip_path = "archive (2).zip"
extract_dir = "autism_data"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_dir)

df = pd.read_csv(os.path.join(extract_dir, "data_csv.csv"))

if "CASE_NO_PATIENT'S" in df.columns:
    df = df.drop(columns=["CASE_NO_PATIENT'S"])

target_col = "ASD_traits"
y = df[target_col]
X = df.drop(columns=[target_col])

if y.dtype == object or not np.issubdtype(y.dtype, np.number):
    le = LabelEncoder()
    y = le.fit_transform(y)

leak_features = [
    'A1','A2','A3','A4','A5','A6','A7','A8','A9','A10_Autism_Spectrum_Quotient',
    'Social_Responsiveness_Scale','Qchat_10_Score','Childhood Autism Rating Scale'
]
X_clean = X.drop(columns=[f for f in leak_features if f in X.columns])

num_cols = X_clean.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X_clean.select_dtypes(include=['object','category']).columns.tolist()

for c in cat_cols:
    if set(X_clean[c].astype(str).str.lower().unique()) <= {'yes','no','0','1','true','false'}:
        X_clean[c] = X_clean[c].astype(str).str.lower().map({'yes':1,'no':0,'true':1,'false':0,'0':0,'1':1})
        num_cols.append(c)

cat_cols = X_clean.select_dtypes(include=['object','category']).columns.tolist()

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y, test_size=0.2, stratify=y, random_state=42
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Train shape:", X_train_processed.shape)
print("Test shape :", X_test_processed.shape)
print("Numeric cols:", num_cols)
print("Categorical cols:", cat_cols)

"""##Classification Techniques"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

clf = RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced')
clf.fit(X_train_processed, y_train)

y_pred = clf.predict(X_test_processed)
y_proba = clf.predict_proba(X_test_processed)[:,1]  # only for binary classification

print("\n--- Model Evaluation ---")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))
print("ROC AUC  :", roc_auc_score(y_test, y_proba))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

# --------- 1. Define parameter grid ---------
param_grid = {
    'max_depth': [3, 5, 7, 9, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10],
    'criterion': ['gini', 'entropy']
}

# --------- 2. Initialize Decision Tree ---------
dt_clf = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# --------- 3. Grid Search with 5-fold CV ---------
grid_search = GridSearchCV(
    estimator=dt_clf,
    param_grid=param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1,
    verbose=1
)

# --------- 4. Train ---------
grid_search.fit(X_train_processed, y_train)

# --------- 5. Best Parameters ---------
print("Best Parameters:", grid_search.best_params_)

# --------- 6. Best Estimator ---------
best_dt = grid_search.best_estimator_

# --------- 7. Predictions ---------
y_pred = best_dt.predict(X_test_processed)

# For binary classification
if len(np.unique(y_train)) == 2:
    y_proba = best_dt.predict_proba(X_test_processed)[:,1]
    roc_auc = roc_auc_score(y_test, y_proba)
else:
    roc_auc = "N/A (multi-class)"

# --------- 8. Evaluation ---------
print("\n--- Tuned Decision Tree Evaluation ---")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))
print("ROC AUC  :", roc_auc)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

# --------- Initialize SVM ---------
# kernel can be 'linear', 'rbf', 'poly', etc.
svm_clf = SVC(kernel='rbf', probability=True, random_state=42, class_weight='balanced')

# --------- Train ---------
svm_clf.fit(X_train_processed, y_train)

# --------- Predictions ---------
y_pred = svm_clf.predict(X_test_processed)
y_proba = svm_clf.predict_proba(X_test_processed)[:,1]  # for ROC AUC

# --------- Evaluation ---------
print("\n--- SVM Evaluation ---")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))
print("ROC AUC  :", roc_auc_score(y_test, y_proba))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

# --------- Base learners ---------
# Tuned XGBoost from your previous step
xgb = XGBClassifier(
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42,
    n_estimators=100,
    max_depth=7,
    learning_rate=0.01,
    subsample=0.7,
    colsample_bytree=0.7,
    gamma=0.3
)

svm = SVC(kernel='rbf', probability=True, random_state=42, class_weight='balanced')

# --------- Meta-learner ---------
meta_clf = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)

# --------- Stacking Classifier ---------
stacking_clf = StackingClassifier(
    estimators=[('xgb', xgb), ('svm', svm)],
    final_estimator=meta_clf,
    cv=5,
    n_jobs=-1,
    passthrough=True
)

# --------- Train Stacking Classifier ---------
stacking_clf.fit(X_train_processed, y_train)

# --------- Predictions ---------
y_pred = stacking_clf.predict(X_test_processed)
y_proba = stacking_clf.predict_proba(X_test_processed)[:,1]

# --------- Evaluation ---------
print("\n--- Stacked Ensemble (XGBoost + SVM) Evaluation ---")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))
print("ROC AUC  :", roc_auc_score(y_test, y_proba))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import roc_auc_score

# --------- 1. Load Data ---------
df = pd.read_csv("autism_data/data_csv.csv")

# Drop ID column
if "CASE_NO_PATIENT'S" in df.columns:
    df = df.drop(columns=["CASE_NO_PATIENT'S"])

# Target + Features
target_col = "ASD_traits"
y = df[target_col]
X = df.drop(columns=[target_col])

# Encode target if categorical
from sklearn.preprocessing import LabelEncoder
if y.dtype == object or not np.issubdtype(y.dtype, np.number):
    le = LabelEncoder()
    y = le.fit_transform(y)

# --------- 2. Controlled Feature Engineering ---------
# Keep only top correlated features (from correlation analysis)
top_features = ['A9','A6','A7','A5','A1','Qchat_10_Score','Global developmental delay/intellectual disability']

X = X[top_features]

# Aggregate score
X['total_score'] = X[['A1','A5','A6','A7','A9']].sum(axis=1)

# Single interaction feature (avoid too many)
X['Qchat_Age_ratio'] = X['Qchat_10_Score'] / (X['total_score'] + 0.1)

# --------- 3. Identify numeric & categorical columns ---------
num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(include=['object','category']).columns.tolist()

# --------- 4. Preprocessing Pipelines ---------
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

# --------- 5. Train/Test Split ---------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# --------- 6. Base Learners with Regularization ---------
tuned_xgb = XGBClassifier(
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42,
    n_estimators=150,
    max_depth=5,           # shallower tree to avoid overfit
    learning_rate=0.05,    # lower learning rate
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.3,
    min_child_weight=5
)

svm_clf = SVC(kernel='rbf', C=1.0, probability=True, random_state=42, class_weight='balanced')

# --------- 7. Stacked Ensemble ---------
stacking_clf = StackingClassifier(
    estimators=[('xgb', tuned_xgb), ('svm', svm_clf)],
    final_estimator=LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42),
    cv=5,
    passthrough=True,
    n_jobs=-1
)

# --------- 8. Full Pipeline ---------
full_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('stacked', stacking_clf)
])

# --------- 9. Cross-Validation ---------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(full_pipeline, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
print("5-Fold CV Accuracy: %.4f ± %.4f" % (cv_scores.mean(), cv_scores.std()))

# --------- 10. Train Final Model ---------
full_pipeline.fit(X_train, y_train)

# --------- 11. Predictions ---------
y_pred = full_pipeline.predict(X_test)
y_proba = full_pipeline.predict_proba(X_test)[:,1]

# --------- 12. Evaluation ---------
print("\n--- Controlled Feature-Engineered Stacked Ensemble Evaluation ---")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


# Predict probabilities
y_proba = full_pipeline.predict_proba(X_test)[:, 1]

# Compute ROC AUC
roc_auc = roc_auc_score(y_test, y_proba)
print("ROC AUC :", roc_auc)

# ===============================================
# 🧠 Autism Detection Using Stacked Model (XGBoost + SVM)
# ===============================================

# 📦 Step 1. Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import StackingClassifier

# 📥 Step 2. Load Dataset
df = pd.read_csv("/content/archive (4).zip")   # <-- change path if needed
target_col = "ASD_traits"

# Encode target if it’s categorical
if df[target_col].dtype == "object":
    le = LabelEncoder()
    df[target_col] = le.fit_transform(df[target_col])

y = df[target_col]
X = df.drop(columns=[target_col])

print(f"✅ Loaded shape: {df.shape}")
print(f"🎯 Target column: {target_col}")

# 🔍 Step 3. Remove ID / leakage columns
id_like = [c for c in X.columns if "id" in c.lower() or "case" in c.lower() or "patient" in c.lower()]
X.drop(columns=id_like, inplace=True, errors="ignore")

diagnostic_like = [
    "Childhood Autism Rating Scale",
    "A10_Autism_Spectrum_Quotient",
    "Social_Responsiveness_Scale",
    "Qchat_10_Score"
]
leak_cols = [c for c in X.columns if any(key.lower() in c.lower() for key in diagnostic_like)]
X.drop(columns=leak_cols, inplace=True, errors="ignore")

print(f"🧹 Columns after cleanup: {X.shape[1]}")

# 🔢 Step 4. Handle numeric + categorical features
num_cols = X.select_dtypes(include=np.number).columns.tolist()
cat_cols = X.select_dtypes(exclude=np.number).columns.tolist()

numeric_transformer = Pipeline([
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, cat_cols)
])

# ⚙️ Step 5. Define models
xgb = XGBClassifier(
    learning_rate=0.05,
    n_estimators=250,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"
)

svm = SVC(kernel="rbf", probability=True, C=2, gamma="scale", random_state=42)

stacked = StackingClassifier(
    estimators=[("xgb", xgb), ("svm", svm)],
    final_estimator=XGBClassifier(
        learning_rate=0.05,
        n_estimators=150,
        max_depth=4,
        random_state=42,
        use_label_encoder=False,
        eval_metric="logloss"
    ),
    stack_method="predict_proba",
    n_jobs=-1
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", stacked)
])

# 📊 Step 6. Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 🧠 Step 7. 10-Fold Cross Validation
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipeline, X, y, cv=cv, scoring="accuracy", n_jobs=-1)
print(f"\n✅ 10-Fold CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# 🚀 Step 8. Final Training & Evaluation
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
roc = roc_auc_score(y_test, y_proba)
print(f"\n--- Final Test Evaluation ---")
print(f"Accuracy : {acc:.4f}")
print(f"ROC AUC  : {roc:.4f}")
print(classification_report(y_test, y_pred))

# ✅ Feature Importance from Meta-Learner (after fitting)
try:
    final_xgb = pipeline.named_steps["model"].final_estimator
    if hasattr(final_xgb, "feature_importances_"):
        importances = final_xgb.feature_importances_
        plt.figure(figsize=(8, 5))
        plt.title("Top 15 Important Features (XGBoost Meta-Learner)")
        top_idx = np.argsort(importances)[-15:]
        plt.barh(range(len(top_idx)), importances[top_idx])
        plt.yticks(range(len(top_idx)), [f"Feature {i}" for i in top_idx])
        plt.show()
    else:
        print("Meta-learner has no feature_importances_ attribute.")
except Exception as e:
    print("⚠️ Skipping feature importance:", e)

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import permutation_test_score
import numpy as np
import pandas as pd

print("🔍 --- Overfitting & Data Leakage Diagnostics ---")

# --- 1️⃣ Training vs Test Accuracy ---
y_train_pred = pipeline.predict(X_train)
y_test_pred = pipeline.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print(f"\n✅ Training Accuracy: {train_acc:.4f}")
print(f"✅ Test Accuracy:     {test_acc:.4f}")

if train_acc - test_acc > 0.05:
    print("⚠️ Possible overfitting detected (train much higher than test).")
else:
    print("✅ No major overfitting detected (train/test similar).")


# --- 2️⃣ Cross-Validation Stability ---
try:
    print(f"\n📊 Cross-Validation Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    if cv_scores.std() > 0.02:
        print("⚠️ High variance across folds — may overfit on certain splits.")
    else:
        print("✅ CV results stable across folds.")
except NameError:
    print("⚠️ 'cv_scores' not found. Skipping CV stability check.")


# --- 3️⃣ Data Leakage Detection ---
print("\n🧩 Checking for high-correlation leakage features...")

# Encode target numerically
le = LabelEncoder()
y_encoded = le.fit_transform(pd.concat([y_train, y_test]))

# Select only numeric features
num_X = pd.concat([X_train, X_test]).select_dtypes(include=np.number)
corrs = num_X.corrwith(pd.Series(y_encoded))

leak_features = corrs[abs(corrs) > 0.85]
if not leak_features.empty:
    print("⚠️ Potential leakage features detected:\n", leak_features)
else:
    print("✅ No high-correlation leakage detected.")


# --- 4️⃣ Permutation Test ---
print("\n🧪 Running permutation test (this may take a minute)...")

score, perm_scores, pvalue = permutation_test_score(
    pipeline, pd.concat([X_train, X_test]), pd.concat([y_train, y_test]),
    cv=5, n_permutations=30, scoring="accuracy", n_jobs=-1
)

print(f"True Score: {score:.3f}")
print(f"P-value: {pvalue:.5f}")

if pvalue < 0.05:
    print("✅ Model performance is statistically significant (not random).")
else:
    print("⚠️ Model may not be generalizing well — possible overfitting/leakage.")

import joblib
joblib.dump(pipeline, "autism_detection_model.pkl")
from google.colab import files
files.download("autism_detection_model.pkl")

# ===============================================
# 🧠 Autism Detection Using Stacked Model (XGBoost + SVM)
# ===============================================

# 📦 Step 1. Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, roc_auc_score, classification_report,
    confusion_matrix, RocCurveDisplay
)
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import StackingClassifier
import seaborn as sns
import joblib
import os

# ===============================================
# 📥 Step 2. Load Dataset
# ===============================================
df = pd.read_csv("/content/archive (4).zip")  # Change path if needed
target_col = "ASD_traits"

# Encode target
if df[target_col].dtype == "object":
    le = LabelEncoder()
    df[target_col] = le.fit_transform(df[target_col])

y = df[target_col]
X = df.drop(columns=[target_col])

print(f"✅ Loaded shape: {df.shape}")
print(f"🎯 Target column: {target_col}")

# ===============================================
# 🔍 Step 3. Remove ID / Leakage Columns
# ===============================================
id_like = [c for c in X.columns if "id" in c.lower() or "case" in c.lower() or "patient" in c.lower()]
X.drop(columns=id_like, inplace=True, errors="ignore")

diagnostic_like = [
    "Childhood Autism Rating Scale",
    "A10_Autism_Spectrum_Quotient",
    "Social_Responsiveness_Scale",
    "Qchat_10_Score"
]
leak_cols = [c for c in X.columns if any(key.lower() in c.lower() for key in diagnostic_like)]
X.drop(columns=leak_cols, inplace=True, errors="ignore")

print(f"🧹 Columns after cleanup: {X.shape[1]}")

# ===============================================
# 🔢 Step 4. Handle Numeric + Categorical Features
# ===============================================
num_cols = X.select_dtypes(include=np.number).columns.tolist()
cat_cols = X.select_dtypes(exclude=np.number).columns.tolist()

numeric_transformer = Pipeline([
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, cat_cols)
])

# ===============================================
# ⚙️ Step 5. Define Models
# ===============================================
xgb = XGBClassifier(
    learning_rate=0.05,
    n_estimators=250,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"
)

svm = SVC(kernel="rbf", probability=True, C=2, gamma="scale", random_state=42)

stacked = StackingClassifier(
    estimators=[("xgb", xgb), ("svm", svm)],
    final_estimator=XGBClassifier(
        learning_rate=0.05,
        n_estimators=150,
        max_depth=4,
        random_state=42,
        use_label_encoder=False,
        eval_metric="logloss"
    ),
    stack_method="predict_proba",
    n_jobs=-1
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", stacked)
])

# ===============================================
# 📊 Step 6. Train-Test Split
# ===============================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ===============================================
# 🧠 Step 7. Cross-Validation
# ===============================================
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipeline, X, y, cv=cv, scoring="accuracy", n_jobs=-1)

print(f"\n✅ 10-Fold CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# ===============================================
# 🚀 Step 8. Final Training & Evaluation
# ===============================================
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
roc = roc_auc_score(y_test, y_proba)
report = classification_report(y_test, y_pred, output_dict=True)

print("\n--- Final Test Evaluation ---")
print(f"Accuracy : {acc:.4f}")
print(f"ROC AUC  : {roc:.4f}")
print(classification_report(y_test, y_pred))

# ===============================================
# 📈 Step 9. Visualization Directory
# ===============================================
os.makedirs("/content/autism_output", exist_ok=True)

# ---- ROC Curve ----
plt.figure()
RocCurveDisplay.from_predictions(y_test, y_proba)
plt.title("ROC Curve - Stacked XGBoost + SVM")
plt.savefig("/content/autism_output/fig_roc.png", dpi=300, bbox_inches="tight")
plt.close()

# ---- Confusion Matrix ----
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.savefig("/content/autism_output/fig_confusion.png", dpi=300, bbox_inches="tight")
plt.close()

# ---- Accuracy Summary ----
plt.figure(figsize=(6, 4))
plt.bar(["Train/Test Mean CV"], [cv_scores.mean() * 100])
plt.ylim(0, 100)
plt.ylabel("Accuracy (%)")
plt.title("10-Fold CV Accuracy Summary")
plt.savefig("/content/autism_output/fig_accuracy.png", dpi=300, bbox_inches="tight")
plt.close()

# ---- Feature Importance ----
try:
    final_xgb = pipeline.named_steps["model"].final_estimator
    if hasattr(final_xgb, "feature_importances_"):
        importances = final_xgb.feature_importances_
        plt.figure(figsize=(8, 5))
        plt.title("Top 15 Important Features (XGBoost Meta-Learner)")
        top_idx = np.argsort(importances)[-15:]
        plt.barh(range(len(top_idx)), importances[top_idx])
        plt.yticks(range(len(top_idx)), [f"Feature {i}" for i in top_idx])
        plt.savefig("/content/autism_output/fig_feature_importance.png", dpi=300, bbox_inches="tight")
        plt.close()
    else:
        print("⚠️ Meta-learner has no feature_importances_ attribute.")
except Exception as e:
    print("⚠️ Skipping feature importance:", e)

# ===============================================
# 💾 Step 10. Save Model and Metrics
# ===============================================
joblib.dump(pipeline, "/content/autism_output/autism_detection_model.joblib")

metrics_summary = {
    "Accuracy": acc,
    "ROC_AUC": roc,
    "Precision": report["1"]["precision"],
    "Recall": report["1"]["recall"],
    "F1-Score": report["1"]["f1-score"],
    "CV_Mean": cv_scores.mean(),
    "CV_Std": cv_scores.std()
}
pd.DataFrame([metrics_summary]).to_csv("/content/autism_output/model_metrics_summary.csv", index=False)

print("\n✅ All outputs saved in /content/autism_output:")
print(" - fig_roc.png")
print(" - fig_confusion.png")
print(" - fig_accuracy.png")
print(" - fig_feature_importance.png")
print(" - autism_detection_model.joblib")
print(" - model_metrics_summary.csv")
# ===============================================
# 📊 Compare Accuracy of SVM, XGBoost, and Hybrid Model
# ===============================================

from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Split data again (in case not defined)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    stratify=y,
                                                    random_state=42)

# --- 1️⃣ Train SVM Model ---
svm_clf = Pipeline([
    ("preprocessor", preprocessor),
    ("svm", SVC(kernel="rbf", probability=True, C=2, gamma="scale", random_state=42))
])
svm_clf.fit(X_train, y_train)
svm_acc = accuracy_score(y_test, svm_clf.predict(X_test))

# --- 2️⃣ Train Tuned XGBoost Model ---
xgb_clf = Pipeline([
    ("preprocessor", preprocessor),
    ("xgb", XGBClassifier(
        learning_rate=0.05,
        n_estimators=250,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        use_label_encoder=False,
        eval_metric="logloss"
    ))
])
xgb_clf.fit(X_train, y_train)
xgb_acc = accuracy_score(y_test, xgb_clf.predict(X_test))

# --- 3️⃣ Hybrid Stacked Model (SVM + XGBoost) ---
stacked_clf = Pipeline([
    ("preprocessor", preprocessor),
    ("model", StackingClassifier(
        estimators=[("xgb", xgb_clf.named_steps["xgb"]),
                    ("svm", svm_clf.named_steps["svm"])],
        final_estimator=XGBClassifier(
            learning_rate=0.05,
            n_estimators=150,
            max_depth=4,
            random_state=42,
            use_label_encoder=False,
            eval_metric="logloss"
        ),
        stack_method="predict_proba",
        n_jobs=-1
    ))
])
stacked_clf.fit(X_train, y_train)
hybrid_acc = accuracy_score(y_test, stacked_clf.predict(X_test))

# --- 📈 Plot Comparison ---
models = ["SVM", "XGBoost", "Hybrid (SVM+XGB)"]
accuracies = [svm_acc * 100, xgb_acc * 100, hybrid_acc * 100]

plt.figure(figsize=(8, 5))
bars = plt.bar(models, accuracies, color=["skyblue", "orange", "seagreen"])
plt.title("Model Accuracy Comparison", fontsize=13)
plt.ylabel("Accuracy (%)")
plt.ylim(80, 100)
plt.grid(axis='y', alpha=0.3)

# Add text labels on bars
for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() - 1,
             f"{bar.get_height():.2f}%", ha="center", va="bottom", fontsize=11, color="black")

plt.tight_layout()
plt.savefig("/content/autism_output/fig_model_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

print(f"SVM Accuracy: {svm_acc:.4f}")
print(f"XGBoost Accuracy: {xgb_acc:.4f}")
print(f"Hybrid (SVM+XGBoost) Accuracy: {hybrid_acc:.4f}")

